name: simplicity
display_name: Simplicity
version: 1.0.0
author:
  name: "TekapoCart"
  email: "hi@tekapo.io"
  url: "https://www.tekapo.io"

meta:
  compatibility:
      from: 1.7.6.1
      to: ~

  available_layouts:
    layout-full-width:
      name: 單欄
      description: 無側欄
#    layout-both-columns:
#      name: Three Columns
#      description: One large central column and 2 side columns.
    layout-left-column:
      name: 雙欄，左窄右寬
      description: 輔助內容位於主要內容左邊
    layout-right-column:
      name: 雙欄，右窄左寬
      description: 輔助內容位於主要內容右邊

assets:
  # If you're using this theme as child and you want to load
  # the parent theme assets, uncomment this line.
#  use_parent_assets: true

  # The following lines are showing how to load assets in your page
  # Uncomment and change value to start loading css or js files
#  css:
#    all:
#      - id: custom-lib-style
#        path: assets/css/custom-lib.css
#    product:
#      - id: product-style
#        path: assets/css/product.css
#        media: all
#        priority: 200
#  js:
#    cart:
#      - id: cat-extra-lib
#        path: assets/js/cart-lib.js


global_settings:
  configuration:
    PS_IMAGE_QUALITY: png_all
  modules:
   to_enable:
     - ps_linklist
     - simplicity_logo
  hooks:
    modules_to_hook:
      displayBanner:
        - simplicity_headerbar
        - ps_imageslider
      displayNav1:
        - simplicity_logo
        - ps_mainmenu
      displayNav2:
        - ps_searchbar
        - ps_languageselector
        - ps_currencyselector
        - ps_customersignin
        - ps_shoppingcart
      displayTop:
      displayHome:
        - ps_featuredproducts
        - ps_banner
        - ps_customtext
        - simplicity_igfeed
      displayFooterBefore:
        - ps_bestsellers
        - ps_emailsubscription
        - ps_socialfollow
      displayFooter:
        - ps_linklist
      displayFooterAfter:
        - simplicity_footerbar
      displayLeftColumn:
        - ps_categorytree
        - ps_facetedsearch
#      displayRightColumn:
#        - ps_categorytree
#        - ps_facetedsearch
      displayLeftColumnProduct:
        - ps_categorytree
#      displayRightColumnProduct:
#        - ps_categorytree
      displaySearch:
        - ps_searchbar
      displayProductAdditionalInfo:
        - ps_sharebuttons
        - ps_viewedproduct
      displayReassurance:
      displayOrderConfirmation1:
      displayOrderConfirmation2:
      displayCrossSellingShoppingCart:

  image_types:
    cart_default:
      width: 125
      height: 125
      scope: []
    small_default:
      width: 300
      height: 300
      scope: [products, categories, manufacturers, suppliers]
    medium_default:
      width: 452
      height: 452
      scope: [manufacturers, suppliers]
    home_default:
      width: 500
      height: 500
      scope: [products]
    large_default:
      width: 800
      height: 800
      scope: [products, manufacturers, suppliers]
    category_default:
      width: 141
      height: 180
      scope: [categories]
    stores_default:
      width: 170
      height: 115
      scope: [stores]

theme_settings:
  default_layout: layout-full-width
  layouts:
    category: layout-left-column
    product: layout-left-column
    best-sales: layout-left-column
    new-products: layout-left-column
    viewed-products: layout-left-column
    prices-drop: layout-left-column
    contact: layout-left-column
