DELETE FROM ps_meta_lang WHERE id_meta IN (54, 55, 56, 57, 58);

INSERT INTO `ps_meta_lang` (`id_meta`, `id_shop`, `id_lang`, `title`, `description`, `keywords`, `url_rewrite`) VALUES
(54, 1, 1, '點數回饋', '', '', 'reward-points'),
(54, 1, 2, 'Reward Points', '', '', 'reward-points'),
(54, 1, 3, 'Reward Points', '', '', 'reward-points'),
(54, 1, 4, 'Reward Points', '', '', 'reward-points'),
(54, 2, 1, '點數回饋', '', '', 'reward-points'),
(54, 2, 2, 'Reward Points', '', '', 'reward-points'),
(54, 2, 3, 'Reward Points', '', '', 'reward-points'),
(54, 2, 4, 'Reward Points', '', '', 'reward-points'),
(54, 3, 1, '點數回饋', '', '', 'reward-points'),
(54, 3, 2, 'Reward Points', '', '', 'reward-points'),
(54, 3, 3, 'Reward Points', '', '', 'reward-points'),
(54, 3, 4, 'Reward Points', '', '', 'reward-points'),
(54, 4, 1, '點數回饋', '', '', 'reward-points'),
(54, 4, 2, 'Reward Points', '', '', 'reward-points'),
(54, 4, 3, 'Reward Points', '', '', 'reward-points'),
(54, 4, 4, 'Reward Points', '', '', 'reward-points'),
(55, 1, 1, '部落格分類', '', '', ''),
(55, 1, 2, 'Blog Categories', '', '', ''),
(55, 1, 3, 'Blog Categories', '', '', ''),
(55, 1, 4, 'Blog Categories', '', '', ''),
(55, 2, 1, '部落格分類', '', '', ''),
(55, 2, 2, 'Blog Categories', '', '', ''),
(55, 2, 3, 'Blog Categories', '', '', ''),
(55, 2, 4, 'Blog Categories', '', '', ''),
(55, 3, 1, '部落格分類', '', '', ''),
(55, 3, 2, 'Blog Categories', '', '', ''),
(55, 3, 3, 'Blog Categories', '', '', ''),
(55, 3, 4, 'Blog Categories', '', '', ''),
(55, 4, 1, '部落格分類', '', '', ''),
(55, 4, 2, 'Blog Categories', '', '', ''),
(55, 4, 3, 'Blog Categories', '', '', ''),
(55, 4, 4, 'Blog Categories', '', '', ''),
(56, 1, 1, '部落格文章', '', '', 'blog'),
(56, 1, 2, 'Blog', '', '', 'blog'),
(56, 1, 3, 'Blog', '', '', 'blog'),
(56, 1, 4, 'Blog', '', '', 'blog'),
(56, 2, 1, '部落格文章', '', '', 'blog'),
(56, 2, 2, 'Blog', '', '', 'blog'),
(56, 2, 3, 'Blog', '', '', 'blog'),
(56, 2, 4, 'Blog', '', '', 'blog'),
(56, 3, 1, '部落格文章', '', '', 'blog'),
(56, 3, 2, 'Blog', '', '', 'blog'),
(56, 3, 3, 'Blog', '', '', 'blog'),
(56, 3, 4, 'Blog', '', '', 'blog'),
(56, 4, 1, '部落格文章', '', '', 'blog'),
(56, 4, 2, 'Blog', '', '', 'blog'),
(56, 4, 3, 'Blog', '', '', 'blog'),
(56, 4, 4, 'Blog', '', '', 'blog'),
(57, 1, 1, '部落格搜尋', '', '', ''),
(57, 1, 2, 'Blog Search', '', '', ''),
(57, 1, 3, 'Blog Search', '', '', ''),
(57, 1, 4, 'Blog Search', '', '', ''),
(57, 2, 1, '部落格搜尋', '', '', ''),
(57, 2, 2, 'Blog Search', '', '', ''),
(57, 2, 3, 'Blog Search', '', '', ''),
(57, 2, 4, 'Blog Search', '', '', ''),
(57, 3, 1, '部落格搜尋', '', '', ''),
(57, 3, 2, 'Blog Search', '', '', ''),
(57, 3, 3, 'Blog Search', '', '', ''),
(57, 3, 4, 'Blog Search', '', '', ''),
(57, 4, 1, '部落格搜尋', '', '', ''),
(57, 4, 2, 'Blog Search', '', '', ''),
(57, 4, 3, 'Blog Search', '', '', ''),
(57, 4, 4, 'Blog Search', '', '', ''),
(58, 1, 1, '部落格首頁', '', '', 'blogs'),
(58, 1, 2, 'Blogs', '', '', 'blogs'),
(58, 1, 3, 'Blogs', '', '', 'blogs'),
(58, 1, 4, 'Blogs', '', '', 'blogs'),
(58, 2, 1, '部落格首頁', '', '', 'blogs'),
(58, 2, 2, 'Blogs', '', '', 'blogs'),
(58, 2, 3, 'Blogs', '', '', 'blogs'),
(58, 2, 4, 'Blogs', '', '', 'blogs'),
(58, 3, 1, '部落格首頁', '', '', 'blogs'),
(58, 3, 2, 'Blogs', '', '', 'blogs'),
(58, 3, 3, 'Blogs', '', '', 'blogs'),
(58, 3, 4, 'Blogs', '', '', 'blogs'),
(58, 4, 1, '部落格首頁', '', '', 'blogs'),
(58, 4, 2, 'Blogs', '', '', 'blogs'),
(58, 4, 3, 'Blogs', '', '', 'blogs'),
(58, 4, 4, 'Blogs', '', '', 'blogs');

-- id_module 104 不該有 carrier
SELECT * FROM `ps_module_carrier` WHERE `id_module` = 104 ORDER BY `id_module` ASC;
SELECT * FROM `ps_module_currency` WHERE `id_module` = 104;