UPDATE `ps_tab_lang` SET `name` = '客戶管理' WHERE `ps_tab_lang`.`id_tab` = 24 AND `ps_tab_lang`.`id_lang` = 1;
UPDATE `ps_tab_lang` SET `name` = '客戶列表' WHERE `ps_tab_lang`.`id_tab` = 25 AND `ps_tab_lang`.`id_lang` = 1;
UPDATE `ps_tab_lang` SET `name` = '客戶地址' WHERE `ps_tab_lang`.`id_tab` = 26 AND `ps_tab_lang`.`id_lang` = 1;
UPDATE `ps_tab_lang` SET `name` = '訂單管理' WHERE `ps_tab_lang`.`id_tab` = 3 AND `ps_tab_lang`.`id_lang` = 1;
UPDATE `ps_tab_lang` SET `name` = '訂單列表' WHERE `ps_tab_lang`.`id_tab` = 4 AND `ps_tab_lang`.`id_lang` = 1;
UPDATE `ps_tab_lang` SET `name` = '加入購物車紀錄' WHERE `ps_tab_lang`.`id_tab` = 8 AND `ps_tab_lang`.`id_lang` = 1;
UPDATE `ps_tab_lang` SET `name` = '商品管理' WHERE `ps_tab_lang`.`id_tab` = 9 AND `ps_tab_lang`.`id_lang` = 1;
UPDATE `ps_tab_lang` SET `name` = '商品列表' WHERE `ps_tab_lang`.`id_tab` = 10 AND `ps_tab_lang`.`id_lang` = 1;
UPDATE `ps_tab_lang` SET `name` = '分類列表' WHERE `ps_tab_lang`.`id_tab` = 11 AND `ps_tab_lang`.`id_lang` = 1;
UPDATE `ps_tab_lang` SET `name` = '商品規格＆特色' WHERE `ps_tab_lang`.`id_tab` = 13 AND `ps_tab_lang`.`id_lang` = 1;
UPDATE `ps_tab_lang` SET `name` = '規格列表' WHERE `ps_tab_lang`.`id_tab` = 14 AND `ps_tab_lang`.`id_lang` = 1;
UPDATE `ps_tab_lang` SET `name` = '特色列表' WHERE `ps_tab_lang`.`id_tab` = 15 AND `ps_tab_lang`.`id_lang` = 1;
UPDATE `ps_tab_lang` SET `name` = '庫存管理' WHERE `ps_tab_lang`.`id_tab` = 23 AND `ps_tab_lang`.`id_lang` = 1;
UPDATE `ps_tab_lang` SET `name` = '商品監控' WHERE `ps_tab_lang`.`id_tab` = 12 AND `ps_tab_lang`.`id_lang` = 1;
UPDATE `ps_tab_lang` SET `name` = '檔案列表' WHERE `ps_tab_lang`.`id_tab` = 19 AND `ps_tab_lang`.`id_lang` = 1;
UPDATE `ps_tab_lang` SET `name` = '優惠活動' WHERE `ps_tab_lang`.`id_tab` = 21 AND `ps_tab_lang`.`id_lang` = 1;
UPDATE `ps_tab_lang` SET `name` = '客服問答' WHERE `ps_tab_lang`.`id_tab` = 28 AND `ps_tab_lang`.`id_lang` = 1;
UPDATE `ps_tab_lang` SET `name` = '問題列表' WHERE `ps_tab_lang`.`id_tab` = 29 AND `ps_tab_lang`.`id_lang` = 1;
UPDATE `ps_tab_lang` SET `name` = '預設回覆' WHERE `ps_tab_lang`.`id_tab` = 30 AND `ps_tab_lang`.`id_lang` = 1;
UPDATE `ps_tab_lang` SET `name` = '統計報表' WHERE `ps_tab_lang`.`id_tab` = 32 AND `ps_tab_lang`.`id_lang` = 1;
UPDATE `ps_tab_lang` SET `name` = '建置' WHERE `ps_tab_lang`.`id_tab` = 42 AND `ps_tab_lang`.`id_lang` = 1;
UPDATE `ps_tab_lang` SET `name` = '模組位置' WHERE `ps_tab_lang`.`id_tab` = 54 AND `ps_tab_lang`.`id_lang` = 1;
UPDATE `ps_tab_lang` SET `name` = '佈景主題＆模組' WHERE `ps_tab_lang`.`id_tab` = 121 AND `ps_tab_lang`.`id_lang` = 1;
UPDATE `ps_tab_lang` SET `name` = '佈景＆版型' WHERE `ps_tab_lang`.`id_tab` = 50 AND `ps_tab_lang`.`id_lang` = 1;
UPDATE `ps_tab_lang` SET `name` = '金物流串接' WHERE `ps_tab_lang`.`id_tab` = 59 AND `ps_tab_lang`.`id_lang` = 1;
UPDATE `ps_tab_lang` SET `name` = '多國設定' WHERE `ps_tab_lang`.`id_tab` = 62 AND `ps_tab_lang`.`id_lang` = 1;
UPDATE `ps_tab_lang` SET `name` = '本地' WHERE `ps_tab_lang`.`id_tab` = 63 AND `ps_tab_lang`.`id_lang` = 1;
UPDATE `ps_tab_lang` SET `name` = '本地' WHERE `ps_tab_lang`.`id_tab` = 64 AND `ps_tab_lang`.`id_lang` = 1;
UPDATE `ps_tab_lang` SET `name` = '多國語系' WHERE `ps_tab_lang`.`id_tab` = 65 AND `ps_tab_lang`.`id_lang` = 1;
UPDATE `ps_tab_lang` SET `name` = '多國貨幣' WHERE `ps_tab_lang`.`id_tab` = 66 AND `ps_tab_lang`.`id_lang` = 1;
UPDATE `ps_tab_lang` SET `name` = '區域、國家' WHERE `ps_tab_lang`.`id_tab` = 68 AND `ps_tab_lang`.`id_lang` = 1;
UPDATE `ps_tab_lang` SET `name` = 'Traffic & SEO' WHERE `ps_tab_lang`.`id_tab` = 92 AND `ps_tab_lang`.`id_lang` = 1;
UPDATE `ps_tab_lang` SET `name` = 'META＆URL' WHERE `ps_tab_lang`.`id_tab` = 93 AND `ps_tab_lang`.`id_lang` = 1;
UPDATE `ps_tab_lang` SET `name` = '內容' WHERE `ps_tab_lang`.`id_tab` = 117 AND `ps_tab_lang`.`id_lang` = 1;
UPDATE `ps_tab` SET `id_parent` = '117' WHERE `ps_tab`.`id_tab` = 53;
UPDATE `ps_tab` SET `position` = '1' WHERE `ps_tab`.`id_tab` = 53;
UPDATE `ps_tab` SET `position` = '5' WHERE `ps_tab`.`id_tab` = 76;
UPDATE `ps_tab` SET `position` = '4' WHERE `ps_tab`.`id_tab` = 117;
UPDATE `ps_tab` SET `active` = '0' WHERE `ps_tab`.`id_tab` = 92;
UPDATE `ps_tab` SET `id_parent` = '117' WHERE `ps_tab`.`id_tab` = 93;
UPDATE `ps_tab` SET `active` = '0' WHERE `ps_tab`.`id_tab` = 96;
UPDATE `ps_tab` SET `active` = '1' WHERE `ps_tab`.`id_tab` = 117;
UPDATE `ps_tab` SET `active` = '1' WHERE `ps_tab`.`id_tab` = 12;
UPDATE `ps_tab` SET `id_parent` = '5' WHERE `ps_tab`.`id_tab` = 97;
UPDATE `ps_tab_lang` SET `name` = '站內搜尋' WHERE `ps_tab_lang`.`id_tab` = 97 AND `ps_tab_lang`.`id_lang` = 1;
UPDATE `ps_tab` SET `active` = '0' WHERE `ps_tab`.`id_tab` = 85;
UPDATE `ps_tab` SET `id_parent` = '24' WHERE `ps_tab`.`id_tab` = 87;
UPDATE `ps_tab_lang` SET `name` = '客戶分級' WHERE `ps_tab_lang`.`id_tab` = 87 AND `ps_tab_lang`.`id_lang` = 1;
UPDATE `ps_tab` SET `id_parent` = '24' WHERE `ps_tab`.`id_tab` = 88;
UPDATE `ps_tab_lang` SET `name` = '客戶稱謂' WHERE `ps_tab_lang`.`id_tab` = 88 AND `ps_tab_lang`.`id_lang` = 1;
UPDATE `ps_tab_lang` SET `name` = '後台帳號' WHERE `ps_tab_lang`.`id_tab` = 105 AND `ps_tab_lang`.`id_lang` = 1;
UPDATE `ps_tab` SET `id_parent` = '77' WHERE `ps_tab`.`id_tab` = 84;
UPDATE `ps_tab_lang` SET `name` = '商品' WHERE `ps_tab_lang`.`id_tab` = 84 AND `ps_tab_lang`.`id_lang` = 1;
UPDATE `ps_tab` SET `id_parent` = '42' WHERE `ps_tab`.`id_tab` = 90;
UPDATE `ps_tab` SET `id_parent` = '42' WHERE `ps_tab`.`id_tab` = 91;
UPDATE `ps_tab_lang` SET `name` = '商家資訊' WHERE `ps_tab_lang`.`id_tab` = 91 AND `ps_tab_lang`.`id_lang` = 1;
UPDATE `ps_tab_lang` SET `name` = '客服信箱' WHERE `ps_tab_lang`.`id_tab` = 90 AND `ps_tab_lang`.`id_lang` = 1;
UPDATE `ps_tab` SET `position` = '1' WHERE `ps_tab`.`id_tab` = 91;
UPDATE `ps_tab` SET `position` = '2' WHERE `ps_tab`.`id_tab` = 90;
UPDATE `ps_tab` SET `position` = '3' WHERE `ps_tab`.`id_tab` = 50;
UPDATE `ps_tab` SET `position` = '5' WHERE `ps_tab`.`id_tab` = 59;
UPDATE `ps_tab` SET `position` = '6' WHERE `ps_tab`.`id_tab` = 62;
UPDATE `ps_tab` SET `icon` = 'list' WHERE `ps_tab`.`id_tab` = 84;
UPDATE `ps_tab` SET `icon` = 'style' WHERE `ps_tab`.`id_tab` = 97;
UPDATE `ps_tab` SET `icon` = 'library_books' WHERE `ps_tab`.`id_tab` = 53;
UPDATE `ps_tab` SET `icon` = 'beenhere' WHERE `ps_tab`.`id_tab` = 93;
UPDATE `ps_tab` SET `position` = '4' WHERE `ps_tab`.`id_tab` = 42;
UPDATE `ps_tab` SET `position` = '3' WHERE `ps_tab`.`id_tab` = 117;
UPDATE `ps_tab` SET `active` = '1' WHERE `ps_tab`.`id_tab` = 20;
UPDATE `ps_tab` SET `active` = '1' WHERE `ps_tab`.`id_tab` = 22;
UPDATE `ps_tab` SET `id_parent` = '20' WHERE `ps_tab`.`id_tab` = 21;
UPDATE `ps_tab_lang` SET `name` = '優惠券' WHERE `ps_tab_lang`.`id_tab` = 21 AND `ps_tab_lang`.`id_lang` = 1;
UPDATE `ps_tab_lang` SET `name` = '全館特價' WHERE `ps_tab_lang`.`id_tab` = 22 AND `ps_tab_lang`.`id_lang` = 1;
UPDATE `ps_tab` SET `position` = '1' WHERE `ps_tab`.`id_tab` = 21;
UPDATE `ps_tab_lang` SET `name` = '條件折扣、優惠券' WHERE `ps_tab_lang`.`id_tab` = 21 AND `ps_tab_lang`.`id_lang` = 1;
UPDATE `ps_tab_lang` SET `name` = '折扣規則' WHERE `ps_tab_lang`.`id_tab` = 20 AND `ps_tab_lang`.`id_lang` = 1;
UPDATE `ps_tab` SET `id_parent` = '77' WHERE `ps_tab`.`id_tab` = 80;
UPDATE `ps_tab` SET `id_parent` = '42' WHERE `ps_tab`.`id_tab` = 89;
UPDATE `ps_tab` SET `id_parent` = '89' WHERE `ps_tab`.`id_tab` = 91;
UPDATE `ps_tab` SET `id_parent` = '89' WHERE `ps_tab`.`id_tab` = 90;
UPDATE `ps_tab` SET `icon` = 'business' WHERE `ps_tab`.`id_tab` = 89;
UPDATE `ps_tab_lang` SET `name` = '聯絡我們' WHERE `ps_tab_lang`.`id_tab` = 89 AND `ps_tab_lang`.`id_lang` = 1;
UPDATE `ps_tab` SET `position` = '20' WHERE `ps_tab`.`id_tab` = 19;
UPDATE `ps_tab` SET `position` = '10' WHERE `ps_tab`.`id_tab` = 20;
UPDATE `ps_tab_lang` SET `name` = '批次銷貨單下載' WHERE `ps_tab_lang`.`id_tab` = 5 AND `ps_tab_lang`.`id_lang` = 1;
UPDATE `ps_tab` SET `position` = '10' WHERE `ps_tab`.`id_tab` = 87;
UPDATE `ps_tab` SET `position` = '20' WHERE `ps_tab`.`id_tab` = 88;
UPDATE `ps_tab` SET `position` = '4' WHERE `ps_tab`.`id_tab` = 28;
UPDATE `ps_tab` SET `position` = '20' WHERE `ps_tab`.`id_tab` = 5;
UPDATE `ps_tab` SET `position` = '4' WHERE `ps_tab`.`id_tab` = 12;
UPDATE `ps_tab` SET `position` = '3' WHERE `ps_tab`.`id_tab` = 13;
UPDATE `ps_tab` SET `id_parent` = '42' WHERE `ps_tab`.`id_tab` = 53;
UPDATE `ps_tab` SET `id_parent` = '42' WHERE `ps_tab`.`id_tab` = 93;
UPDATE `ps_tab` SET `id_parent` = '42' WHERE `ps_tab`.`id_tab` = 97;
UPDATE `ps_tab` SET `position` = '1' WHERE `ps_tab`.`id_tab` = 50;
UPDATE `ps_tab` SET `position` = '4' WHERE `ps_tab`.`id_tab` = 53;
UPDATE `ps_tab` SET `position` = '7' WHERE `ps_tab`.`id_tab` = 93;
UPDATE `ps_tab` SET `position` = '8' WHERE `ps_tab`.`id_tab` = 97;
UPDATE `ps_tab` SET `id_parent` = '77' WHERE `ps_tab`.`id_tab` = 93;
UPDATE `ps_tab` SET `id_parent` = '77' WHERE `ps_tab`.`id_tab` = 97;
UPDATE `ps_tab` SET `position` = '1' WHERE `ps_tab`.`id_tab` = 103;
UPDATE `ps_tab` SET `position` = '5' WHERE `ps_tab`.`id_tab` = 93;
UPDATE `ps_tab` SET `position` = '2' WHERE `ps_tab`.`id_tab` = 84;
UPDATE `ps_tab` SET `position` = '4' WHERE `ps_tab`.`id_tab` = 97;
UPDATE `ps_tab` SET `position` = '3' WHERE `ps_tab`.`id_tab` = 55;
UPDATE `ps_tab` SET `position` = '6' WHERE `ps_tab`.`id_tab` = 105;
UPDATE `ps_tab` SET `position` = '7' WHERE `ps_tab`.`id_tab` = 80;